import { Card } from "@/components/ui/card";
import { CheckCircle, AlertCircle, Zap } from "lucide-react";

interface ResultCardProps {
  result: {
    success: boolean;
    verdict: "ai" | "human";
    confidence: string;
    detectedGenerator: string | null;
    fileUrl: string;
    processingTimeMs: number;
  };
  fileType?: "image" | "audio" | "video" | null;
  fileName?: string;
}

export default function ResultCard({ result, fileType, fileName }: ResultCardProps) {
  const confidence = parseFloat(result.confidence);
  const isAI = result.verdict === "ai";
  const confidencePercent = (confidence * 100).toFixed(1);

  const getVerdictColor = () => {
    if (isAI) {
      return "text-red-600";
    }
    return "text-green-600";
  };

  const getVerdictBgColor = () => {
    if (isAI) {
      return "bg-red-50 border-red-200";
    }
    return "bg-green-50 border-green-200";
  };

  const getConfidenceColor = () => {
    if (confidence > 0.8) return "text-red-600";
    if (confidence > 0.6) return "text-orange-600";
    if (confidence > 0.4) return "text-yellow-600";
    return "text-green-600";
  };

  const formatGenerator = (generator: string | null) => {
    if (!generator) return "Unknown";
    return generator
      .split("_")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ");
  };

  return (
    <div className="space-y-6">
      {/* Main Verdict Card */}
      <Card className={`border-2 p-8 ${getVerdictBgColor()}`}>
        <div className="flex items-start gap-6">
          <div>
            {isAI ? (
              <AlertCircle className={`w-16 h-16 ${getVerdictColor()}`} />
            ) : (
              <CheckCircle className={`w-16 h-16 ${getVerdictColor()}`} />
            )}
          </div>
          <div className="flex-1">
            <h2 className={`text-4xl font-bold ${getVerdictColor()} mb-2`}>
              {isAI ? "AI-Generated" : "Authentic"}
            </h2>
            <p className="text-slate-700 text-lg">
              {isAI
                ? "This content appears to be generated by artificial intelligence."
                : "This content appears to be authentic and human-created."}
            </p>
          </div>
        </div>
      </Card>

      {/* Details Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Confidence Score */}
        <Card className="border border-slate-200 p-6 bg-white">
          <div className="flex items-center gap-3 mb-4">
            <Zap className="w-5 h-5 text-blue-600" />
            <h3 className="font-semibold text-slate-900">Confidence Score</h3>
          </div>
          <div className="space-y-3">
            <div className={`text-3xl font-bold ${getConfidenceColor()}`}>
              {confidencePercent}%
            </div>
            <div className="w-full bg-slate-200 rounded-full h-3 overflow-hidden">
              <div
                className={`h-full transition-all duration-300 ${
                  isAI
                    ? "bg-gradient-to-r from-red-500 to-red-600"
                    : "bg-gradient-to-r from-green-500 to-green-600"
                }`}
                style={{ width: `${confidence * 100}%` }}
              />
            </div>
            <p className="text-sm text-slate-600">
              {confidence > 0.8
                ? "Very high confidence"
                : confidence > 0.6
                  ? "High confidence"
                  : confidence > 0.4
                    ? "Moderate confidence"
                    : "Low confidence"}
            </p>
          </div>
        </Card>

        {/* File Information */}
        <Card className="border border-slate-200 p-6 bg-white">
          <h3 className="font-semibold text-slate-900 mb-4">File Information</h3>
          <div className="space-y-3">
            {fileName && (
              <div>
                <p className="text-xs text-slate-600 uppercase tracking-wide">File Name</p>
                <p className="text-slate-900 font-medium truncate">{fileName}</p>
              </div>
            )}
            {fileType && (
              <div>
                <p className="text-xs text-slate-600 uppercase tracking-wide">File Type</p>
                <p className="text-slate-900 font-medium capitalize">{fileType}</p>
              </div>
            )}
            <div>
              <p className="text-xs text-slate-600 uppercase tracking-wide">Processing Time</p>
              <p className="text-slate-900 font-medium">{result.processingTimeMs}ms</p>
            </div>
          </div>
        </Card>
      </div>

      {/* Detected Generator */}
      {result.detectedGenerator && isAI && (
        <Card className="border border-slate-200 p-6 bg-slate-50">
          <h3 className="font-semibold text-slate-900 mb-3">Likely Generator</h3>
          <div className="inline-block bg-blue-100 text-blue-800 px-4 py-2 rounded-lg font-medium">
            {formatGenerator(result.detectedGenerator)}
          </div>
          <p className="text-sm text-slate-600 mt-3">
            Based on the analysis, this content appears to have been generated using{" "}
            {formatGenerator(result.detectedGenerator)}.
          </p>
        </Card>
      )}

      {/* Preview */}
      {result.fileUrl && (
        <Card className="border border-slate-200 p-6 bg-white">
          <h3 className="font-semibold text-slate-900 mb-4">Preview</h3>
          {fileType === "image" && (
            <img
              src={result.fileUrl}
              alt="Analyzed content"
              className="w-full rounded-lg max-h-96 object-cover"
            />
          )}
          {fileType === "audio" && (
            <audio controls className="w-full">
              <source src={result.fileUrl} />
              Your browser does not support the audio element.
            </audio>
          )}
          {fileType === "video" && (
            <video controls className="w-full rounded-lg max-h-96">
              <source src={result.fileUrl} />
              Your browser does not support the video element.
            </video>
          )}
        </Card>
      )}

      {/* Disclaimer */}
      <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
        <p className="text-sm text-yellow-900">
          <strong>Note:</strong> This analysis is based on AI detection algorithms and may not be
          100% accurate. Always verify important content through multiple sources and human review
          when necessary.
        </p>
      </div>
    </div>
  );
}
